version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "check-airpurif-avail"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k2bpneh5jck0"
s3_prefix = "check-airpurif-avail"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NotificationEmail=\"\" PurifierModelName=\"AC3059\""

