AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function for checking if selected air purifier is available

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 3
Parameters: 
  PurifierModelName:
    Type: String
Resources:
  CheckPurifAvailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: check_airpurif_avail/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        CheckPurifAvailScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Name: CheckPurifAvailSchedule
            Enabled: False
      Environment: 
        Variables:
          NOTIFICATION_TOPIC: !ImportValue airpurifier-avilable-topic-TopicARN
          PURIFIER_MODEL_NAME: !Ref PurifierModelName

  # AlarmTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     Subscription:
  #     - Protocol: email
  #       Endpoint: !Ref NotificationEmail

  # Alarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmActions:
  #       - !Ref AlarmTopic
  #     ComparisonOperator: GreaterThanOrEqualToThreshold
  #     Dimensions:
  #       - Name: FunctionName
  #         Value: !Ref CheckWebsitePeriodically
  #     EvaluationPeriods: 1
  #     MetricName: Errors
  #     Namespace: AWS/Lambda
  #     Period: 60
  #     Statistic: Sum
  #     Threshold: '1'            

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CheckAirPurifAvailabilityFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CheckPurifAvailFunction.Arn
  CheckAirPurifAvailabilityFunctionRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CheckPurifAvailFunctionRole.Arn
